name: Deploy remix site to Cloudflare Workers

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./web

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: ./web
      - name: Build
        run: npm run build
        working-directory: ./web
      - name: Deploy
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ./web
